#!/usr/bin/env bash
#this script prints bad luck for 4 and good luck for 8
i=1
while ((i <= 10)); do
    if ((i == 4)); then
        echo "bad luck"
    elif ((i == 8)); then
        echo "goog luck"
    else
        echo "Best School"
    fi
        ((i += 1))
done
