#!/usr/bin/env bash
#prints bad luck depends on country
i=1
while ((i <= 20)); do
        echo $i
        case $1 in
                4) echo "bad luck from china";;
                9) echo "bad luck from Japan";;
                17) echo "bad luck from Italy";;
        esac
        ((i+=1))
done
